---
- name: Deploying SSH key on Remote Host
  hosts: targethosts
  remote_user: vagrant
  sudo: true

  tasks:
  - name: Fetch URL
    uri: url="https://raw.githubusercontent.com/mcheriyath/helper-scripts/master/ansiblessh/sample.json" return_content=yes
    register: json_response
    tags:
       - fromjson

  - action: fail
    when: "'key' not in json_response.content"
    tags:
       - fromjson

  - debug: msg="Success - Key Found as =>{{  (json_response.content|from_json)['ssh']['key'] }}<="  
    when:  (json_response.content|from_json)['ssh']['key']  is defined
    tags:
       - fromjson

  - shell: echo "{{ (json_response.content|from_json)['ssh']['key'] }}" >> /home/vagrant/.ssh/authorized_keys
    tags:
       - fromjson

  - authorized_key: user=vagrant key=https://raw.githubusercontent.com/mcheriyath/helper-scripts/master/ansiblessh/pub.key
    tags:
       - frompubkey
