postgresql:
  image: orchardup/postgresql:latest
  environment:
    - POSTGRESQL_USER=sonar
    - POSTGRESQL_PASS=xaexohquaetiesoo
    - POSTGRESQL_DB=sonar
  volumes:
    - /opt/db/sonarqube/:/var/lib/postgresql
  ports:
    - "5432:5432"
sonarqube:
  image: sonarqube
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=xaexohquaetiesoo
    - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.33.56/sonar
  ports:
    - "80:9000"
    - "9092:9092"
